### ISSUE TITLE
Incorrect length passed to `fread` on a flac file

### ISSUE THREAD

**Issue by paulijar** [JamesHeinrich/getID3#351]
I got a sample file from a user which causes an error when being analyzed with getID3. The user reported that this causes a segmentation fault, while I can only see an error being logged but the analysis finishes otherwise fine. My best guess is that maybe the user is using PHP 8 while I have been testing on PHP 7.4.

The relevant part of the stack trace is this:
```
ValueError: fread(): Argument #2 ($length) must be greater than 0 in /var/www/html/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php:2215
Stack trace:
#0 /var/www/html/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php(2215): fread()
#1 /var/www/html/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio.flac.php(408): getid3_handler->fread()
#2 /var/www/html/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio.flac.php(125): getid3_flac->parsePICTURE()
#3 /var/www/html/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio.flac.php(46): getid3_flac->parseMETAdata()
#4 /var/www/html/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php(778): getid3_flac->Analyze()
#5 /var/www/html/nextcloud/apps/music/lib/Utility/ExtractorGetID3.php(75): getID3->analyze()
```

I shall email the sample file shortly.

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/getID3/commit/6f7b917e01992bc4720a90f244254873f9aa86a9
