### ISSUE TITLE
Ampache: Fatal error: Uncaught Error: [] operator not supported for strings in

### ISSUE THREAD

**Issue by pbtrung** [JamesHeinrich/getID3#92]
I encountered this error while scanning my media library using php .../catalog_update.inc -a

......./05-AudioTrack 05.mp3
Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php:926
Stack trace:
#0 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1088): getid3_mp3->decodeMPEGaudioHeader(1757, Array, false)
#1 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(973): getid3_mp3->RecursiveFrameScanning(1757, 2174, false)
#2 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1430): getid3_mp3->decodeMPEGaudioHeader(1757, Array, true)
#3 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(35): getid3_mp3->getOnlyMPEGaudioInfo(1757)
#4 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/getid3.php(450): getid3_mp3->Analyze()
#5 /var/www/html/lib/class/vainfo.class.php(96): getID3->analyze('/media/aub/PEMA...')
#6 /var/www/html/modules/catalog/local/local.catalog.php(674): vainfo->__construct('/media/aub/PEMA...', Array, '', '', '', '%a/%A', '%T - %t')
#7 /var/www in /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php on line 926

Ampache docker: https://github.com/pbtrung/ampache-docker
Ampache 3.8.3-develop, PHP 7, MySQL 5.7, Apache 2.4

Thanks.

**Comment by JamesHeinrich** [comment]
I just made a commit https://github.com/JamesHeinrich/getID3/commit/288293d2a7b95b79e7ef27da957dcdfd89873f62 which standardizes all the warning calls (and https://github.com/JamesHeinrich/getID3/commit/7f069ac25b3d83e849aeefe4f7da660f358b6b25 for errors) which may possibly fix your problem. If it does not, please send me the sample file in question that generates the error.
